apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: h2o
  name: h2o
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: h2o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: h2o
    spec:
      containers:
      - image: docker.io/jasmi111/h2o:latest
        name: h2o
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
