apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: h2o
  name: h2o
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: h2o
    spec:
      containers:
      - image: docker.io/harsha544/h2o:ppc64le
        name: h2o
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
